using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using QIS.Medinfras.Web.Common.UI;
using QIS.Medinfras.Web.Common;
using QIS.Medinfras.Data.Service;
using QIS.Data.Core.Dal;

namespace QIS.Medinfras.Web.MedicalRecord.Program
{
    public partial class VitalSignTypeEntry : BasePageEntry
    {
        public override string OnGetMenuCode()
        {
            return Constant.MenuCode.MedicalRecord.VITAL_SIGN;
        }

        protected string GetPageTitle()
        {
            return hdnPageTitle.Value;
        }

        protected override void InitializeDataControl()
        {
            if (Request.QueryString.Count > 0)
            {
                IsAdd = false;
                String ID = Request.QueryString["id"];
                SetControlProperties();
                hdnID.Value = ID;

                VitalSignType entity = BusinessLayer.GetVitalSignType(Convert.ToInt32(hdnID.Value));
                EntityToControl(entity);
            }
            else
            {
                SetControlProperties();
                IsAdd = true;
            }
            txtVitalSignCode.Focus();

            hdnPageTitle.Value = BusinessLayer.GetMenuMasterList(string.Format("MenuCode = '{0}'", OnGetMenuCode())).FirstOrDefault().MenuCaption;
        }

        protected override void SetControlProperties()
        {
            List<StandardCode> lstStandardCode = BusinessLayer.GetStandardCodeList(string.Format("ParentID = '{0}' AND IsDeleted = 0", Constant.StandardCode.VALUE_TYPE));
            Methods.SetComboBoxField<StandardCode>(cboValueType, lstStandardCode, "StandardCodeName", "StandardCodeID");
            cboValueType.SelectedIndex = 0;
        }

        protected override void OnControlEntrySetting()
        {
            SetControlEntrySetting(txtVitalSignCode, new ControlEntrySetting(true, true, true));
            SetControlEntrySetting(txtVitalSignName, new ControlEntrySetting(true, true, true));
            SetControlEntrySetting(txtShortName, new ControlEntrySetting(true, true, true));
            SetControlEntrySetting(txtInitial, new ControlEntrySetting(true, true, true));
            SetControlEntrySetting(txtFHIRReferenceCode, new ControlEntrySetting(true, true, true));
            SetControlEntrySetting(txtFHIRReferenceName, new ControlEntrySetting(true, true, true));
            SetControlEntrySetting(cboValueType, new ControlEntrySetting(true, true, true));
            SetControlEntrySetting(txtValueCode, new ControlEntrySetting(true, true, true));
            SetControlEntrySetting(txtValueCodeName, new ControlEntrySetting(true, true, false));
            SetControlEntrySetting(txtValueUnit, new ControlEntrySetting(true, true, false));
            SetControlEntrySetting(txtFHIRReferenceUnit, new ControlEntrySetting(true, true, true));

            SetControlEntrySetting(txtDisplayColor, new ControlEntrySetting(false, false, false));
            SetControlEntrySetting(txtDisplayColorPicker, new ControlEntrySetting(true, true, false));
            SetControlEntrySetting(txtVitalSignOrder, new ControlEntrySetting(true, true, true, 0));
            SetControlEntrySetting(txtValueMask, new ControlEntrySetting(true, true, false));
            SetControlEntrySetting(txtChartMinValue, new ControlEntrySetting(true, true, true, 0));
            SetControlEntrySetting(txtChartMaxValue, new ControlEntrySetting(true, true, true, 0));
            SetControlEntrySetting(txtMinNormalValue, new ControlEntrySetting(true, true, true, 0));
            SetControlEntrySetting(txtMaxNormalValue, new ControlEntrySetting(true, true, true, 0));

            SetControlEntrySetting(chkIsAutoGenerated, new ControlEntrySetting(true, true, false));
            SetControlEntrySetting(chkIsDisplayInBanner, new ControlEntrySetting(true, true, false));
            SetControlEntrySetting(chkIsDisplayInChart, new ControlEntrySetting(true, true, false));
            SetControlEntrySetting(chkIsNumericValue, new ControlEntrySetting(true, true, false));
            SetControlEntrySetting(chkIsSpecialIndicator, new ControlEntrySetting(true, true, false));
            SetControlEntrySetting(chkIsUsedBySystem, new ControlEntrySetting(true, true, false));
        }

        private void EntityToControl(VitalSignType entity)
        {
            txtVitalSignCode.Text = entity.VitalSignCode;
            txtVitalSignName.Text = entity.VitalSignName;
            txtShortName.Text = entity.ShortName;
            txtInitial.Text = entity.VitalSignLabel;

            string[] reffInfo = entity.FHIRReferenceInfo.Split('|');
            if (reffInfo.Length>=2)
            {
                txtFHIRReferenceCode.Text = reffInfo[0];
                txtFHIRReferenceName.Text = reffInfo[1];
                txtFHIRReferenceUnit.Text = reffInfo[2];
            }

            cboValueType.Value = entity.GCValueType;
            if (entity.GCValueCode != "")
            {
                StandardCode stdCode = BusinessLayer.GetStandardCode(entity.GCValueCode);
                hdnValueCodeID.Value = stdCode.StandardCodeID.ToString();
                txtValueCode.Text = stdCode.StandardCodeID;
                txtShortName.Text = stdCode.StandardCodeName;
            }
            else
            {
                hdnValueCodeID.Value = "";
                txtValueCode.Text = "";
                txtValueCodeName.Text = "";
            }

            txtValueUnit.Text = entity.ValueUnit;

            txtDisplayColor.Text = txtDisplayColorPicker.Text = entity.DisplayColor;
            txtVitalSignOrder.Text = entity.DisplayOrder.ToString();
            txtValueMask.Text = entity.ValueMask;
            txtChartMinValue.Text = entity.ChartMinValue.ToString();
            txtChartMaxValue.Text = entity.ChartMaxValue.ToString();
            txtMinNormalValue.Text = entity.MinNormalValue.ToString();
            txtMaxNormalValue.Text = entity.MaxNormalValue.ToString();

            chkIsAutoGenerated.Checked = entity.IsAutoGenerated;
            chkIsDisplayInBanner.Checked = entity.IsDisplayInBanner;
            chkIsDisplayInChart.Checked = entity.IsDisplayInChart;
            chkIsNumericValue.Checked = entity.IsNumericValue;
            chkIsSpecialIndicator.Checked = entity.IsSpecialIndicator;
            chkIsUsedBySystem.Checked = entity.IsUsedBySystem;
        }

        private void ControlToEntity(VitalSignType entity)
        {
            entity.VitalSignCode = txtVitalSignCode.Text;
            entity.VitalSignName = txtVitalSignName.Text;
            entity.ShortName = txtShortName.Text;
            entity.VitalSignLabel = txtInitial.Text;
            entity.FHIRReferenceInfo = string.Format("{0}|{1}|{2}",txtFHIRReferenceCode.Text, txtFHIRReferenceName.Text,txtFHIRReferenceUnit.Text);
            entity.GCValueType = cboValueType.Value.ToString();
            entity.GCValueCode = txtValueCode.Text;
            entity.ValueUnit = txtValueUnit.Text;
            entity.DisplayColor = txtDisplayColor.Text;
            entity.DisplayOrder = Convert.ToInt16(txtVitalSignOrder.Text);            
            entity.ValueMask = txtValueMask.Text;
            entity.ChartMinValue = Convert.ToInt32(txtChartMinValue.Text);
            entity.ChartMaxValue = Convert.ToInt32(txtChartMaxValue.Text);
            entity.MinNormalValue = Convert.ToDecimal(txtMinNormalValue.Text);
            entity.MaxNormalValue = Convert.ToDecimal(txtMaxNormalValue.Text);

            entity.IsAutoGenerated = chkIsAutoGenerated.Checked;
            entity.IsDisplayInBanner = chkIsDisplayInBanner.Checked;
            entity.IsDisplayInChart = chkIsDisplayInChart.Checked;
            entity.IsNumericValue = chkIsNumericValue.Checked;
            entity.IsSpecialIndicator = chkIsSpecialIndicator.Checked;
            entity.IsUsedBySystem = chkIsUsedBySystem.Checked;
        }

        protected override bool OnBeforeSaveAddRecord(ref string errMessage)
        {
            errMessage = string.Empty;

            string FilterExpression = string.Format("VitalSignCode = '{0}'", txtVitalSignCode.Text);
            List<VitalSignType> lst = BusinessLayer.GetVitalSignTypeList(FilterExpression);

            if (lst.Count > 0)
                errMessage = " Vaccination with Code " + txtVitalSignCode.Text + " is already exist!";

            return (errMessage == string.Empty);
        }

        protected override bool OnBeforeSaveEditRecord(ref string errMessage)
        {
            errMessage = string.Empty;
            Int32 ID = Convert.ToInt32(hdnID.Value);
            string FilterExpression = string.Format("VitalSignCode = '{0}' AND VitalSignID != {1}", txtVitalSignCode.Text, ID);
            List<VitalSignType> lst = BusinessLayer.GetVitalSignTypeList(FilterExpression);

            if (lst.Count > 0)
                errMessage = " VitalSign with Code " + txtVitalSignCode.Text + " is already exist!";

            return (errMessage == string.Empty);
        }

        protected override bool OnSaveAddRecord(ref string errMessage, ref string retval)
        {
            IDbContext ctx = DbFactory.Configure(true);
            VitalSignTypeDao entityDao = new VitalSignTypeDao(ctx);
            bool result = false;
            try
            {
                VitalSignType entity = new VitalSignType();
                ControlToEntity(entity);
                entity.CreatedBy = AppSession.UserLogin.UserID;
                entityDao.Insert(entity);
                retval = BusinessLayer.GetVitalSignTypeMaxID(ctx).ToString();
                ctx.CommitTransaction();
                result = true;
            }
            catch (Exception ex)
            {
                ctx.RollBackTransaction();
                result = false;
                errMessage = ex.Message;
            }
            finally
            {
                ctx.Close();
            }
            return result;
        }

        protected override bool OnSaveEditRecord(ref string errMessage)
        {
            try
            {
                VitalSignType entity = BusinessLayer.GetVitalSignType(Convert.ToInt32(hdnID.Value));
                ControlToEntity(entity);
                entity.LastUpdatedBy = AppSession.UserLogin.UserID;
                BusinessLayer.UpdateVitalSignType(entity);
                return true;
            }
            catch (Exception ex)
            {
                errMessage = ex.Message;
                return false;
            }
        }

    }
}